### ISSUE TITLE
Maximum call stack size exceeded error when running action on my private repo

### ISSUE THREAD

**Issue by atul-exabeam** [advanced-security/maven-dependency-submission-action#13]
Error: RangeError: Maximum call stack size exceeded
Error: Error: Could not generate a snapshot of the dependencies; Maximum call stack size exceeded
Error: Failed to generate a dependency snapshot, check logs for more details, Error: Could not generate a snapshot of the dependencies; Maximum call stack size exceeded

**Comment by kaihendry** [comment]
I hit this error too: https://github.com/kaihendry/mvn-java-test/actions/runs/3880262987/jobs/6618175278

**Comment by dominiquedejaeger-liantis** [comment]
I am getting this error too.

**Comment by peter-murray** [comment]
Fixed in version `v3.0.0` as it now accommodates the full Maven coordinate system in the PackageURLs
