### ISSUE TITLE
Manifest file path should be relative to `GITHUB_WORKSPACE`

### ISSUE THREAD

**Issue by juxtin** [advanced-security/maven-dependency-submission-action#18]
When constructing a [manifest object](https://github.com/advanced-security/maven-dependency-submission-action/blob/0b9cd8f382c5d2016fa77ebf8a0f2804452fefef/src/depgraph.ts#L77), `filePath` is currently the full absolute path to the file, including the prefix `/home/runner/work/my-repo-name/my-repo-name`.

That prefix ends up being displayed in the Dependency Graph, where it:
* looks weird
* breaks links to the original file
* can result in duplicate alerts

Ideally, we would check for `GITHUB_WORKSPACE` in the env (it _should_ always be there) and strip its value from the beginning of the `filePath` argument.

**Comment by peter-murray** [comment]
I take it that this request is in relation to how this works currently, i.e. the `v1` `v2` tags?

The snapshot toolkit added some optional support for project names and file rendering that has resulted in a number of changes in the `multi-module` branch that accommodates this already.

There are some complexities in how this works though, as it makes a number of assumptions that this is doing the "default" behaviours on things like checkout in a an actions workflow.

**Comment by peter-murray** [comment]
I have just released version `v3.0.0` that should accommodate this use case.
