### ISSUE TITLE
Flag `--branch-ref` doesn't work in v3

### ISSUE THREAD

**Issue by luigigubello** [advanced-security/maven-dependency-submission-action#26]
The binary file `maven-dependency-tree-submission-linux` **v3** seems not working properly using the flag `-b`.
I have tested both [attached binaries](https://github.com/advanced-security/maven-dependency-submission-action/actions/runs/4245323023) and compiled binaries (running `npm run base-build` and `npm run build-exe`).

Using the command:
````
maven-dependency-tree-submission-linux --token "$GITHUB_TOKEN" --repository "$GITHUB_REPOSITORY" --branch-ref "$GITHUB_REF" --sha "$GITHUB_SHA" --directory "$MY_PATH" --job-name "$MY_JOB"
````
It always returns this error: `Branch reference must be in path form, e.g. 'refs/heads/main' for the 'main' branch.`
Even if my branch is `refs/heads/main`

Binary file **v2.0.1** works as expected using that command.

**Screenshot**
<img width="629" alt="Screenshot 2023-02-23 at 11 49 16" src="https://user-images.githubusercontent.com/27034386/220909965-b37f873e-12f4-4ad7-b65c-d73f26ed6b9f.png">

**Comment by peter-murray** [comment]
Fixed in `v3`, `v3.0` and `v3.0.1` tags sha `d682d5d68a398c90e9b35f8c564cd8e1918d6a24`
