### ISSUE TITLE
Global JOB worker directory does not affect the settings.

### ISSUE THREAD

**Issue by hantsy** [advanced-security/maven-dependency-submission-action#34]
My project is under `api` in the repository.

I have tried to set `directory: api`, it will search wrong path in the log. (`/home/runner/work/spring-security-reactive-auth0-sample/spring-security-reactive-auth0-sample/api/api/mvn`)

or using job level worker directory, both are failed.

Check the build log when using global work directory.

https://github.com/hantsy/spring-security-reactive-auth0-sample/actions/runs/4729915186/jobs/8392963583

```bash 
 Error:  Failed to execute goal com.github.ferstl:depgraph-maven-plugin:4.0.2:reactor (default-cli): Goal requires a project to execute but there is no POM in this directory (/home/runner/work/spring-security-reactive-auth0-sample/spring-security-reactive-auth0-sample). Please verify you invoked Maven from the correct directory. -> [Help 1]
  Error:  
  Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
  Error:  Re-run Maven using the -X switch to enable full debug logging.
  Error:  
  Error:  For more information about the errors and possible solutions, please read the following articles:
  Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

```

**Comment by peter-murray** [comment]
This is an encapsulated action that just happens to utilize a maven command line internally. The `directory` input parameter on the action is there to allow you to direct it to the correct maven root location of your project for it to analyze.

The default setting for the `directory` for the action mirrors that for the `actions/checkout` action which is the `github.workspace` directory.

If you set the directory to an absolute path where you need to run from, it should execute correctly, so a setting of `directory: ${{ github.workspace }}/api` would work as intended.

When I forked your repository by the way, the executable bit on the `mvnw` file is not set so you will need that correctly set as the action will pick up that file and try to use it unless you disable the action from using the provide `mnvw`

**Comment by peter-murray** [comment]
Closing this issue due to lack of response and a solution above.
