### ISSUE TITLE
Submission lack `context` and `job` when submitted through GitHub Actions

### ISSUE THREAD

**Issue by louis-bompart** [advanced-security/maven-dependency-submission-action#39]
I think the [context ](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) is never set when `maven-dependency-submission-action` is used as an action:

- We create the Snapshot here with `snapshotConfig.context` for the context.
https://github.com/advanced-security/maven-dependency-submission-action/blob/d682d5d68a398c90e9b35f8c564cd8e1918d6a24/src/snapshot-generator.ts#L46
- `snapshotConfig` is defined as the 3rd argument of `generateSnapshot`.
https://github.com/advanced-security/maven-dependency-submission-action/blob/d682d5d68a398c90e9b35f8c564cd8e1918d6a24/src/snapshot-generator.ts#L26
- `generateSnapshot` is called in `index.js`. The 3rd param does not have a context property.
https://github.com/advanced-security/maven-dependency-submission-action/blob/d682d5d68a398c90e9b35f8c564cd8e1918d6a24/src/index.ts#L18

The same applies for `job`.

This issue does not happen with the CLI because a fake GitHub aActions context is generated:
https://github.com/advanced-security/maven-dependency-submission-action/blob/d682d5d68a398c90e9b35f8c564cd8e1918d6a24/src/executable/cli.ts#L46-L54

**Comment by peter-murray** [comment]
The snapshot toolkit loads the context and job details from the actions runtime environment, it is contained in that library (as it expects an Actions environment). Do you have some specific failure or error that is occurring here?

**Comment by louis-bompart** [comment]
My bad!

I was so focused on the creation of the Snapshot that I didn't check the submit function of the toolkit.
We had some issues with some dependabot alerts not being closed properly closed up, but that was already reported/taken care of, I just missed the memo. 

For completeness' sake:

The context is injected there:
https://github.com/advanced-security/maven-dependency-submission-action/blob/c5ad0fd6b977364190852883b46728f25a9617c3/src/index.ts#L30
Because context is defaulting https://github.com/github/dependency-submission-toolkit/blob/a4b38a11e9429b8d086d766e2380620743c80a5f/src/snapshot.ts#L169

Thanks for your time 😄
