### ISSUE TITLE
Publish executables package to release

### ISSUE THREAD

**Issue by coheigea** [advanced-security/maven-dependency-submission-action#54]
I'd like to re-use the executables built as part of https://github.com/advanced-security/maven-dependency-submission-action/actions/workflows/publish_executables.yml to integrate the tool with our Jenkins builds, however it's not very user friendly having to use a URL like https://github.com/advanced-security/maven-dependency-submission-action/actions/runs/6573953252 in a script and it requires authentication to be able to download the zip file. Could the zip be uploaded instead to the release for https://github.com/advanced-security/maven-dependency-submission-action/releases/tag/v3.0.3 for easy download?

**Comment by peter-murray** [comment]
I have not finished development of these yet as need to provide a testing mechanism for them, that is why they are artifacts for now.

**Comment by peter-murray** [comment]
These are now integrated in to the releases for each version.
