### ISSUE TITLE
Getting 403 even if permissions:write is set

### ISSUE THREAD

**Issue by coheigea** [advanced-security/maven-dependency-submission-action#55]
Hi,

In an open-source project we are using this action as follows: https://github.com/apache/santuario-xml-security-java/blob/main/.github/workflows/dependency-submission.yml

When I (who have write access) submit a PR everything works fine. However as you can see in this PR https://github.com/apache/santuario-xml-security-java/pull/240 the action fails with:
```
Error: HTTP Status 403 for request POST https://api.github.com/repos/apache/santuario-xml-security-java/dependency-graph/snapshots
Error: Response body:
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/dependency-graph/dependency-submission#create-a-snapshot-of-dependencies-for-a-repository"
}
```
contents: write is set as a permission for the job. What am I doing wrong here please?

**Comment by peter-murray** [comment]
The failing linked PR check workflow, shows permissions of `read` and not the required `write` here; https://github.com/apache/santuario-xml-security-java/actions/runs/6738707294/workflow

**Comment by peter-murray** [comment]
Looking a little further around your runs for that workflow, I think the issue lies in the permissions you are allowing for Pull Requests from forks of your repository. GitHub Actions treats these as risky and by default you have to opt into allowing permissions higher that write.

**Comment by peter-murray** [comment]
For additional context and help on deciding what is right for your use case, this blog post should be able to help you; https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by d-ryan-ashcraft** [comment]
I ran into the same issue and this guidance resolved it for me.  Thanks @peter-murray!
