### ISSUE TITLE
Missing Maven wrapper support

### ISSUE THREAD

**Issue by thweiss** [advanced-security/maven-dependency-submission-action#6]
It would be great if the `mvn` call was not [hardcoded ](https://github.com/advanced-security/maven-dependency-submission-action/blob/571e99aab1055c2e71a1e2309b9691de18d6b7d6/src/snapshot-generator.ts#L58) and the action would also check for presence of `mvnw`.

As a workaround we're currently executing `cp mvnw /usr/local/bin/mvn` before running the action.

**Comment by peter-murray** [comment]
Support added in `v3.0.0`
