### ISSUE TITLE
:grey_question: Do the `/test-data/maven` projects need to contain vulnerable packages

### ISSUE THREAD

**Issue by ranma2913** [advanced-security/maven-dependency-submission-action#68]
Do the `/test-data/maven` projects need to contain vulnerable packages or could everything get updated?

**Comment by yogurtearl** [comment]
Mentioning in old vulnerable versions of dependencies in `test-data/ and `src/depgraph.test.ts` sets off alarm bells with vulnerability scans. 

Even though they are only used for testing, would be great if those could be updated via dependabot to avoid the false alarms.

**Comment by peter-murray** [comment]
I do need vulnerable dependencies inside my test data. When you say things are setting of alarm bells, where specifically is this happening for you?

**Comment by yogurtearl** [comment]
A security scan of the entire repo looking for vulnerable dependencies sees these old deps mentioned and assumes they are used at runtime in the action. It is not smart enough to realize these are only used in the tests and aren't actually a problem. 

So it causes false positives, which means that using this action gets flagged for using an action with vulnerable dependencies.

**Comment by yogurtearl** [comment]
Do they need to be real deps? could you invent some fake deps with fake vulns to use in the test data?

**Comment by yogurtearl** [comment]
Just to confirm my understanding, none of the maven deps mentioned in the `/test-data` folder are downloaded, packaged, used or executed during the consumption/execution of this action?

**Comment by yogurtearl** [comment]
is there a specific test that would fail if none of the deps had vulnerabilities? (trying to understand how the tests work) 

Could we put the test data is a separate git repo and clone/include that repo for the tests?

**Comment by peter-murray** [comment]
The POMs are there so I can test and validate that when reported we get necessary alerts, i.e. the reported vulnerable packages are correctly being identified if provided by this action to the repository. I also use these tests internally in the Codespace for the action to validate a number of edge cases when I need to.

These are all submitted as results to this repository as part of tests, they are not used here in any way other than to run tests. Adding yet another repository to do all this decouples and greatly complicates testing. validation and gating of releases as well as needing additional cross repository access tokens which is just as bad if not worse.

These test data POMs are not part of the action at execution time, and are only test data. Moving them externally does not remove other aspects like the fact that I report them on this repository as dependencies and I need them in this repository to be able to validate paths when I report them (yet another integration test).

**Comment by stevologic** [comment]
I would like to offer a viewpoint and a solution.

There is a conflict with the structure of this project (using manifest files with vulnerabilities for testing), and the feature it's integrating with (A capability that scans manifest files within a repository and reports on risk).

Suggesting to move ./test-data/ to another repository and use it as a submodule when required, which would alleviate friction when introducing security automation using Dependabot; specifically, when using this action, it would not be flagged.

**Comment by peter-murray** [comment]
It’s a possibility, but at the cost expense of convenience and having to wire up the registry that the poms would be published to. GitHub packages maven registry could work, but it requires a number of changes for local and CI testing workflows.

I have left GitHub and this project remains as part of the Open Source management of the Field Security Specialists team at GitHub, so it would be up to them to decide/implement and take this forward.

/cc @nickliffen for comment

**Comment by peter-murray** [comment]
Note, a move to immutable actions publishing longer term might also be a viable mitigation as people will not be pulling down the whole repository when that happens, so local files like these test file will not be present inside the action.
