### ISSUE TITLE
Missing support to specify additional Maven options

### ISSUE THREAD

**Issue by thweiss** [advanced-security/maven-dependency-submission-action#7]
We would appreciate if there was a way to add additional Maven options:

- setting the location of `settings.xml` via `-s` (workaround: `cp settings.xml ~/.m2/settings.xml`)
- enabling batch mode (`-B`)
- ...

Looks like `MAVEN_ARGS` env var is not picked up currently.

**Comment by peter-murray** [comment]
Support added in version `v3.0.0`
