### ISSUE TITLE
Missing action input to change API endpoint for GitHub Enterprise

### ISSUE THREAD

**Issue by thweiss** [advanced-security/maven-dependency-submission-action#8]
There is no way to adjust the API endpoint to point to a GitHub Enterprise installation when using the action.

In such an environment all API calls produce errors such as:

`Error: HTTP Status 500 for request POST [https://api.github.com/repos](https://api.github.com/repos/<org>/<repo>/dependency-graph/snapshots)`

**Comment by peter-murray** [comment]
This is resolved in the updated toolkit in `v3.0.0`
