### ISSUE TITLE
When should we use this as opposed to the "Automatic dependency submission"

### ISSUE THREAD

**Issue by yeikel** [advanced-security/maven-dependency-submission-action#91]
Hi team, 

As per the docs, a repository owner can [enable "Automatic Dependency Submission" ](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-automatic-dependency-submission-for-your-repository#enabling-automatic-dependency-submission) from the repository settings

Could you please clarify if this action is still relevant given that option? 

It is a bit unclear what the difference or advantages are of using this action directly as the docs suggest that it uses this action to accomplish it

Thanks!

**Comment by jonjanego** [comment]
Hi @yeikel - generally speaking, Automatic dependency submission intends to replace the need to setup this action in your repo. However, in some circumstances where your app doesn't work with automatic dependency submission, you can still use this action to do the submission.

For net-new configurations of dependency submission for Maven, we'd recommend using automatic dependency submission unless you find a compelling reason why it doesn't work well for you.

**Comment by yeikel** [comment]
> Hi @yeikel - generally speaking, Automatic dependency submission intends to replace the need to setup this action in your repo. However, in some circumstances where your app doesn't work with automatic dependency submission, you can still use this action to do the submission.
> 
> For net-new configurations of dependency submission for Maven, we'd recommend using automatic dependency submission unless you find a compelling reason why it doesn't work well for you. 

Thank you for clarifying

**Comment by pa-rj** [comment]
I am using the "automatic deps sub" option in a repo which has a private package dependency (another github repo).
This was working fine for months until 2 days ago it broke. I get now get a 401 when maven tries to access the repo inside the action run.

The interesting thing is, the PATs I'm using have not expired for normal actions/depbot (but I have updated them anyways), repo/package exists, no changes were made in permissions for a long time. Normal action builds are working, which are obviously downloading those private packages just fine (i cleared cache too).

The only thing I can notice that has changed is `v5` release of this action recently.

Does the new version not work with setups like this anymore? Is manual the way to go?

**Comment by yeikel** [comment]
> I am using the "automatic deps sub" option in a repo which has a private package dependency (another github repo).
> This was working fine for months until 2 days ago it broke. I get now get a 401 when maven tries to access the repo inside the action run.
> 
> The interesting thing is, the PATs I'm using have not expired for normal actions/depbot (but I have updated them anyways), repo/package exists, no changes were made in permissions for a long time. Normal action builds are working, which are obviously downloading those private packages just fine (i cleared cache too).
> 
> The only thing I can notice that has changed is `v5` release of this action recently.
> 
> Does the new version not work with setups like this anymore? Is manual the way to go?

You should consider starting a new thread about this

**Comment by dbelyaev** [comment]
> I am using the "automatic deps sub" option in a repo which has a private package dependency (another github repo).
This was working fine for months until 2 days ago it broke. I get now get a 401 when maven tries to access the repo inside the action run.
>
> The interesting thing is, the PATs I'm using have not expired for normal actions/depbot (but I have updated them anyways), repo/package exists, no changes were made in permissions for a long time. Normal action builds are working, which are obviously downloading those private packages just fine (i cleared cache too).
>
> The only thing I can notice that has changed is v5 release of this action recently.
>
> Does the new version not work with setups like this anymore? Is manual the way to go?

@pa-rj did you find a fix for this?

**Comment by andre-HiD** [comment]
> > I am using the "automatic deps sub" option in a repo which has a private package dependency (another github repo).
> > This was working fine for months until 2 days ago it broke. I get now get a 401 when maven tries to access the repo inside the action run.
> > The interesting thing is, the PATs I'm using have not expired for normal actions/depbot (but I have updated them anyways), repo/package exists, no changes were made in permissions for a long time. Normal action builds are working, which are obviously downloading those private packages just fine (i cleared cache too).
> > The only thing I can notice that has changed is `v5` release of this action recently.
> > Does the new version not work with setups like this anymore? Is manual the way to go?
> 
> You should consider starting a new thread about this

@yeikel @jonjanego A new thread regarding this topic was started (https://github.com/advanced-security/maven-dependency-submission-action/issues/115) but no news as of yet. Explicitly using the published action as part of a workflow and setting the `token` input seems to work, but goes against the recommendation given in this very thread.
